apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namePrefix: prod-

replicas:
- name: log-collector
  count: 5
- name: log-processor
  count: 10

commonLabels:
  environment: production
