apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: log-processing
data:
  RABBITMQ_HOST: "rabbitmq-headless.log-processing.svc.cluster.local"
  RABBITMQ_PORT: "5672"
  STORAGE_REPLICAS: "5"
  QUERY_COORDINATOR_PORT: "8080"
  LOG_LEVEL: "INFO"
  PARTITION_COUNT: "12"
