apiVersion: v1
kind: Service
metadata:
  name: storage-headless
  namespace: log-processing
spec:
  clusterIP: None
  selector:
    app: storage-node
  ports:
  - port: 9090
    targetPort: 9090
    name: storage
