apiVersion: v1
kind: Service
metadata:
  name: query-coordinator
  namespace: log-processing
spec:
  type: ClusterIP
  selector:
    app: query-coordinator
  ports:
  - port: 8080
    targetPort: 8080
    name: http
