apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

namespace: log-processing

replicas:
- name: query-coordinator
  count: 5
- name: log-collector
  count: 3

patches:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 5
  target:
    kind: StatefulSet
    name: storage-node
