apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: log-processing

resources:
- namespace/namespace.yaml
- configmaps/app-config.yaml
- secrets/app-secrets.yaml
- storage/statefulset.yaml
- storage/service.yaml
- rabbitmq/statefulset.yaml
- rabbitmq/service.yaml
- query-coordinator/deployment.yaml
- query-coordinator/service.yaml
- log-collector/deployment.yaml
- dashboard/deployment.yaml
- dashboard/service.yaml
